#!/usr/bin/python

import unittest

class BinTestCase(unittest.TestCase):

class BarnTestCase(unittest.TestCase):

class ApplicationTestCase(unittest.TestCase):

if __name__ == '__main__':
    unittest.main()
